name: Echo GitHub SHA

on: [pull_request]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo GitHub SHA
        run: echo ${{ github.sha }}

      - name: Echo GitHub PR Head SHA
        run: echo ${{ github.event.pull_request.head.sha }}