name: Echo GitHub SHA

on:
  pull_request:
    types:
      - closed

jobs:
  echo:
    name: Echo GitHub SHA
    runs-on: ubuntu-latest
    steps:
      - name: Echo GitHub SHA
        run: echo ${{ github.sha }}

      - name: Echo GitHub PR Head SHA
        run: echo ${{ github.event.pull_request.head.sha }}

      - name: Echo GitHUb merge commit SHA
        run: echo ${{ github.event.pull_request.merge_commit_sha }}