name: Tests

on:
  pull_request:
    # Further explanation of the "synchronize" event: https://github.community/t/what-is-a-pull-request-synchronize-event/14784
    types: [opened, synchronize, reopened]

jobs:
  setup:
    name: Setup
    uses: ./.github/workflows/reusable-node-setup.yml

  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Run unit tests
        run: yarn test